#!/bin/bash

F='.cotest'
O='.cotest/stdout'
R=''
V=''
while getopts 'f:o:rv' opt; do
	case $opt in
	f)	F="$OPTARG"
		;;
	o)	O="$OPTARG"
		;;
	r)	R=1
		;;
	v)	V=1
		;;
	*)	usage
		;;
	esac
done
shift $(($OPTIND - 1))

cotest="$PWD/$1"
libdir="$PWD"
cobalt="$PWD/cobalt"

output=`env \
	FIXTURE=$F \
	VALGRIND=$V \
	COTEST=$cotest \
	LIBDIR=$libdir \
	COBALT=$cobalt \
	RUN=$R \
	script/do-cotest 2>&1`
rc=$?
if [ $rc != 0 ]; then
	echo "$output"
	exit $rc
else
	echo "$output" > $O
	exit 0
fi
